
name: greeting-self-hosted_context
on: [workflow_dispatch]
jobs:
  sample-self-hosted:
    runs-on: self-hosted
    steps:
      - name: PRINT GTEETING
        run: echo "hello"
      - name: PRINT done
        run:  |
           echo "First output"
           echo "${{toJSON(github)}}"
