
name: greeting
on: [workflow_dispatch]
jobs:
  sample:
    runs-on: self_hosted
    steps:
      - name: PRINT GTEETING
        run: echo "hello"
      - name: PRINT done
        run:  |
           echo "First output"
           echo "Second output"
