
name: get_secreat
on: [workflow_dispatch]
jobs:
  sample-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Get Secret
        env:
          SECRET_KEY: ${{ secrets.SNST_NAME }}
        run:  |
            echo $SECRET_KEY
            if [ -n "$SECRET_KEY" ]; then
             echo "SECRET_KEY is set"
            else
             echo "SECRET_KEY is not set"
            fi
