
name: greeting_ubuntu
on: [workflow_dispatch]
jobs:
  sample-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: PRINT GTEETING
        run: echo "hello"
      - name: PRINT done
        env:
          SECRET_KEY: ${{ secrets.SNST_NAME }}
        run:  |
           echo "First output"
           echo "Second output"
           echo $SECRET_KEY
