
name: first_action
on: [workflow_dispatch]
jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - name: PRINT GTEETING
        run: echo "hello"
      - name: PRINT done 
        run: echo "done"
