name: SET OUTPUT PARAMETER

on: [workflow_dispatch]

jobs:
 job1:
  runs-on: self-hosted
  steps:
    - name: Set color
      id: color-selector
      run: echo "SELECTED_COLOR=green" >> "$GITHUB_OUTPUT"
    - name: Get color
      env:
        SELECTED_COLOR: ${{ steps.color-selector.outputs.SELECTED_COLOR }}
#        SELECTED_COLOR: 'green'
      run: echo 'The selected color is ${{ env.SELECTED_COLOR }}'
