name: Generate random failure steps context
#on: push
on: [workflow_dispatch]

jobs:
  randomly-failing-job:
    runs-on: self-hosted
    steps:
      # - id: checkout
      #   uses: actions/checkout@v3
      - name: Generate 0 or 1
        id: generate_number
        run:  echo "random_number=$(($RANDOM % 2))" >> $GITHUB_OUTPUT
      - name: Pass or fail
        run: |
          if [[ ${{ steps.generate_number.outputs.random_number }} == 0 ]]; then exit 0; else exit 1;
          else exit 1; fi
